name: Build (multitarget)
on:
  workflow_dispatch: 
    inputs: 
      target_branch:
        description: "Target branch (based on 1.20)"
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        base_branch: ["1.21", "1.19.4", "1.19.3", "1.19.2", "1.18.2", "1.16.5", "1.20.2", "1.20.4", "1.20.6", "1.20"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.target_branch }}
      
      - name: Cherry-pick base + feature
        shell: bash
        run: |
          git checkout ${{ matrix.base_branch }}
          git cherry-pick ^1.20..${{ inputs.target_branch }} || exit 1

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: true

      - name: Build using Gradle
        run: ./gradlew build

      - name: Upload Fabric artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: Fabric-${{matrix.base_branch}}-Artifacts
          path: fabric/build/libs/

      - name: Upload Forge artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: Forge-${{matrix.base_branch}}-Artifacts
          path: forge/build/libs/